<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PaymentAccount;

class PaymentAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accounts = [
            'Advances',
            'Action Research',
            'BPEAP Scholars',
            'Battery Exam',
            'CAV',
            'Certification',
            'COMPRE',
            'Course Audit',
            'Capping',
            'Completion Form',
            'Copy of Grades',
            'Diploma (Recopy)',
            'Down Payment',
            'Documentary Stamp',
            'Exam Permit',
            'Exess Budget',
            'F137-A',
            'Final Defense',
            'Foundation Day Fee',
            'Full Payment',
            'Grace Assessment',
            'Graduation Fee',
            'HD',
            'ID Lace',
            'Insurance',
            'Library Card',
            'Assessment Form',
            'Makeup Duty',
            'Monthly',
            'Notarial Fee',
            'Oral Defense',
            'Over Payment',
            'Penalty',
            'Pre-Oral Defense',
            'Promotion',
            'Red Cross',
            'RLE',
            'Repairs and Maintenance',
            'Reservation Fee',
            'Review',
            'Ringhop',
            'Salary Loan',
            'Special Permit',
            'Sports Fee',
            'SD',
            'Salaries and Wages',
            'Summer Affiliation Fee',
            'SSS Loan',
            'TDP Scholars',
            'Transportation',
            'TOR',
            'Tuition Fee (EBD Scholars)',
            'Tuition Fee',
            'Turnitin',
            'TW1',
            'TW2',
            'Advanced Payment',
            'CTC',
            'With Holding Tax',
            'TWAS',
            'Qualifying Exam',
            'PROFESSIONAL FEE',
            'Course Syllabus',
            'STUDENT ACTIVITIES',
            'Registration Form',
            'School Supplies',
            'OFFICE EQUIPMENT',
            'MEALS & TRANSPO.',
            'PROCTOR',
            'PHOTOCOPY',
            'Token',
            'SSS Premium',
            'Enrollment Form',
            'Communication Expense',
            'Classroom Equipment',
            'Tutorial',
            'Books',
            'Furniture & Fixture',
            'Classroom Furniture& Fixture',
            'Management Fee',
            'Retake Compre',
            'Teacher Subsidy',
            'Cash Advance',
            'Training and Seminar',
            'Seminar Expense',
            'SALARY',
            'OFFICE SHARE',
            'ID',
            'Student Account Payroll',
            'Special Exam',
            'REPRESENTATION EXP.',
            'TRANSPORTATION & TRAVELLING',
            'ATHLETIC EXP.',
            'GMC / DOCS.',
            'Certification / Docs.',
            'Students Activities',
            'TOR / Docs.',
            'TOR/ RLE/DOCS.',
            'Course Description/ RLE/ Docs.',
            'Affiliation Fee',
            'Course Description',
            'DIPLOMA / DOCS',
        ];

        foreach ($accounts as $description) {
            PaymentAccount::create(['description' => $description]);
        }
    }
}
